jugmac00/flask-reuploaded

.travis.yml
CHANGES.rst

This fixes #3
new file:   .travis.yml

Setup CI (Travis)

---

CHANGES.rst
README.rst
flask_uploads.py
setup.py
tests.py

modified:   README.rst
modified:   flask_uploads.py
modified:   setup.py
modified:   tests.py

Rename package from `Flask-Uploads` to `Flask-Reuploaded`

---

.gitignore
CHANGES.rst
pyproject.toml
setup.py

modified:   .gitignore
new file:   pyproject.toml
modified:   setup.py

Prepare release

---

CHANGES.rst
README.rst
setup.py

modified:   README.rst
modified:   setup.py

Back to development

---

PACKAGING.rst

This fixes #28
new file:   PACKAGING.rst

Add packaging guide

---

CHANGES.rst
README.rst

Add migration guide

---

CHANGES.rst
README.rst

Add badges to README

---

.travis.yml

Activate coveralls

---

example/photolog.py
flask_uploads.py
tests.py
tox.ini

modified:   example/photolog.py
modified:   flask_uploads.py
modified:   tests.py
modified:   tox.ini

Force single line imports

---

CHANGES.rst
CONTRIBUTING.rst
README.rst

new file:   CONTRIBUTING.rst
modified:   README.rst

Add contributing guide

---

CHANGES.rst
src/flask_uploads/__init__.py
src/flask_uploads/backwards_compatibility.py
src/flask_uploads/extensions.py
src/flask_uploads/flask_uploads.py
src/flask_uploads/test_helper.py
tox.ini

modified:   src/flask_uploads/__init__.py
modified:   src/flask_uploads/backwards_compatibility.py
modified:   src/flask_uploads/extensions.py
modified:   src/flask_uploads/flask_uploads.py
modified:   src/flask_uploads/test_helper.py
modified:   tox.ini

Add type annotations

---

.gitignore
.pre-commit-config.yaml
MANIFEST.in
docs/conf.py
example/photolog.py
tox.ini

modified:   .gitignore
modified:   .pre-commit-config.yaml
modified:   MANIFEST.in
modified:   docs/conf.py
modified:   example/photolog.py
modified:   tox.ini

Update linter setup

---

.pre-commit-config.yaml

Removed seed-isort-config repo as its deprecated

---

README.rst

Add requires.io and license badges

---

src/flask_uploads/test_helper.py
tests/test_flask_reuploaded.py
tox.ini

fixes #50
modified:   src/flask_uploads/test_helper.py
modified:   tests/test_flask_reuploaded.py
modified:   tox.ini

Add test for UploadNotAllowed

---

.pre-commit-config.yaml
MANIFEST.in

modified:   .pre-commit-config.yaml
modified:   MANIFEST.in

Add check-manifest to pre-commit configuration

---

src/flask_uploads/flask_uploads.py
tests/test_flask_reuploaded.py

fixes #9
modified:   src/flask_uploads/flask_uploads.py
modified:   tests/test_flask_reuploaded.py

Update module docstrings

---

README.rst

improve wording

---

.gitignore
MANIFEST.in
docs/requirements.txt
src/.readthedocs.yaml
tox.ini

also, try to fix autodoc generation on readthedocs

add tox env for docs

---

README.rst

update README: add first incompatibility between Flask-Reuploaded

---

.github/workflows/main.yml
CHANGES.rst
setup.py
tox.ini

Add support for Python 3.10

---

src/flask_uploads/extensions.py
src/flask_uploads/flask_uploads.py
tests/test_autoserve.py
tests/test_flask_reuploaded.py
tox.ini

A couple of edge cases got ingored for now.

Add type annotations to tests

---

CHANGES.rst
docs/conf.py
setup.py
tests/test_flask_reuploaded.py

Fix deprecation warning for pytest

---

.readthedocs.yaml
tox.ini

Changes:
- add build info:
- os version: `ubuntu-22.04`
- os tools: `python`: `3.11`
- add this version for compability to `tox.ini`:
`basepython = python3.11`

add version for build
